### PR TITLE
Use ActiveSupport::Notifications to allow support for Postgres too

### PR DESCRIPTION
**Pull request by cantino**
Also significantly less monkey patching.

### CODE REVIEW

**Comment by diclophis** [comment]
looks mostly good to me...

**Comment by rogerneel** [comment]
@cantino he's back! Nice work, LGTM - especially the move from `"` to `'` ;)

I assume you've tried it with Postgres?

**Comment by naiyt** [comment]
Me looking at the Mavenlink GitHub activity feed

**Comment by cantino** [comment]
Haha, hello!

Yes, I tested it on Postgres, but not MySQL, if one of you would like to try it on Mavenlink.

**Comment by diclophis** [comment]
Judging by that regex refactor I am not sure we can trust this gem any more

**Comment by rogerneel** [comment]
NOT MySQL?! What have you become? I don't even know you anymore maaaaannn...

Ok, we'll test it and merge if 👍

**Comment by cantino** [comment]
Fixed a load ordering bug.  Should be good to go if MySQL still works.

**Comment by bgreg** [comment]
All the tests still pass! 👍

**Comment by cantino** [comment]
Feel free to merge Mavenlink peeps.

**Comment by cantino** [comment]
👍

**Pull request merged**
